version: 0.2

phases:
  install:
    commands:
      - echo Installing dependency...
      - npm install -g react
      - yarn
  pre_build:
    commands:
      - echo Pre build started on `date`
  build:
    commands:
      - echo Compiling the Node.js code
      - npm run build
   post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync ./build/web s3://www.springjh.kr
      - aws cloudfront create-invalidation --distribution-id EC1ZY46GZAUBK --paths  "/*"
artifacts:
  files:
    - '**/*'